<?php

/**
 * BaseProducto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property enum $unidad
 * @property integer $precio_compra
 * @property integer $precio_venta
 * 
 * @method integer  getId()            Returns the current record's "id" value
 * @method string   getNombre()        Returns the current record's "nombre" value
 * @method enum     getUnidad()        Returns the current record's "unidad" value
 * @method integer  getPrecioCompra()  Returns the current record's "precio_compra" value
 * @method integer  getPrecioVenta()   Returns the current record's "precio_venta" value
 * @method Producto setId()            Sets the current record's "id" value
 * @method Producto setNombre()        Sets the current record's "nombre" value
 * @method Producto setUnidad()        Sets the current record's "unidad" value
 * @method Producto setPrecioCompra()  Sets the current record's "precio_compra" value
 * @method Producto setPrecioVenta()   Sets the current record's "precio_venta" value
 * 
 * @package    bazar
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProducto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('producto');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('nombre', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 45,
             ));
        $this->hasColumn('unidad', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'centrimetro',
              1 => 'gramo',
              2 => 'metro',
              3 => 'unidad',
              4 => 'kilo',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('precio_compra', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('precio_venta', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}