ajax_getnombres:
  url:   /getNombres
  param:  { module: AdministrarProductos, action: getNombres }

producto:
  class: sfDoctrineRouteCollection
  options:
    model:                Producto
    module:               AdministrarProductos
    prefix_path:          /AdministrarProductos
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }
homepage:
  url:   /
  param: { module: AdministrarProductos, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
