generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Producto
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          producto
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        hide: [id]
        title: Listado Productos en el Local
        display: [id,nombre,precio_venta]
        max_per_page: 20
      filter:
        display: [nombre]
      form:    ~
      edit:    
        actions:
          _delete: ~
          _list: ~
          _save: ~
          guardar:
            label: Nuevo 
      new:     ~
