<?php

/**
 * ProductoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Producto');
    }
    public static function getNombres($string)
    {
      $q= Doctrine_Query::create()
            ->select('p.nombre')
            ->from('Producto p')
            ->where('LOWER(p.nombre) LIKE ?', '%'.$string.'%')
            ->orderBy('p.nombre DESC')
            ->distinct()
            ->fetchArray();
return $q;   
 }
}
