<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/06/08 16:31:26

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=bazarolga',
  'username' => 'root',
  'password' => 'caronates/recytics',
  'name' => 'doctrine',
)),);
