<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/08 16:31:26
sfConfig::add(array(
  'mod_administrarproductos_enabled' => true,
  'mod_administrarproductos_view_class' => 'sfPHP',
));
